name: Docker and .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: HelloWOrld Build the Docker image and run .NET App
      run: docker build ./HelloWorld/
    - name: StringLibrary Build the Docker image and run .NET App
      run: docker build ./ClassLibraryProjects/StringLibrary
    - name: Test a .NET class library
      run: docker build ./ClassLibraryProjects/StringLibraryTest
